const constants = {
  SUCCESS_CODE: "0000",
  SUCCESS_MESSAGE: "Success",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  DUPLICATE_KEY_ERROR: "DUPLICATE_KEY_ERROR",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  INPUT_VALIDATION_FAIL: "Input Validation Failed",
};

module.exports = constants;
